export const Users = [
    {
      id:1,
      profilePicture: "person/1.jpeg",
      username: "Sarah Newark",
    },
    {
      id:2,
      profilePicture: "person/2.jpeg",
      username: "John Williams",
    },
    {
      id:3,
      profilePicture: "person/3.jpeg",
      username: "Anthony Richardson",
    },
    {
      id:4,
      profilePicture: "person/4.jpeg",
      username: "Katelyn Durden",
    },
    {
      id:5,
      profilePicture: "person/5.jpeg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "person/6.jpeg",
      username: "Amy Renault",
    },
    {
      id:7,
      profilePicture: "person/7.jpeg",
      username: "Valerie Virtuez",
    },
    {
      id:8,
      profilePicture: "person/8.jpeg",
      username: "Daniella Giampetro",
    },
    {
      id:9,
      profilePicture: "person/9.jpeg",
      username: "Jacob Appleby",
    },
    {
      id:10,
      profilePicture: "person/10.png",
      username: "Eddie Holden",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Helping our community and environment!",
      photo: "post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Lets clean the beaches together!",
      photo: "post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Got to make sure we keep Gainesville clean",
      photo: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Lets help the environment by cleaning up guys!",
      photo: "post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];

  export const EventsSide = [
    {
      id:1,
      picture: "events/1.jpeg",
      name: "Gators vs Bulldogs post-game cleanup!",
    },
    {
      id:2,
      picture: "events/2.jpeg",
      name: "Beach cleanup",
    },
    {
      id:3,
      picture: "events/3.jpeg",
      name: "Lets cleanup campus!",
    },
    {
      id:4,
      picture: "events/4.jpeg",
      name: "Help clean downtown!",
    },
    {
      id:5,
      picture: "events/5.jpeg",
      name: "Lets cleanup Gainesville together!",
    },
    {
      id:6,
      picture: "events/6.jpeg",
      name: "Downtown Orlando cleanup",
    },
    {
      id:7,
      picture: "events/7.jpeg",
      name: "Cleanup Ocala!",
    },
    {
      id:8,
      picture: "events/8.jpeg",
      name: "Lets clean St.Augustine",
    },
  ];

  export const Events = [
    {
      id: 1,
      desc: "Helping our community and environment!",
      photo: "events/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      signedUp: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "events/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      signedUp: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Lets clean the beaches together!",
      photo: "events/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      signedUp: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "events/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      signedUp: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "events/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      signedUp: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "events/6.jpeg",
      date: "1 day ago",
      userId: 6,
      signedUp: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Got to make sure we keep Gainesville clean",
      photo: "events/7.jpeg",
      date: "2 days ago",
      userId: 7,
      signedUp: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "events/8.jpeg",
      date: "3 days ago",
      userId: 8,
      signedUp: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Lets help the environment by cleaning up guys!",
      photo: "events/9.jpeg",
      date: "5 days ago",
      userId: 9,
      signedUp: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "events/10.jpeg",
      date: "1 week ago",
      userId: 10,
      signedUp: 104,
      comment: 12,
    },
  ];